### PR TITLE
feat: upgrade from latest vscode-eslint

### LINKED ISSUE #117: Doesn't work with esLint 8.x
I believe due to this: https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0#removal-of-undocumented-apis-removal-of-cliengine-and-linter

Eslint works fine from the command line, but I"m getting this error in VIM:

```The eslint library loaded from [.....]/node_modules/eslint/lib/api.js doesn't export a CLIEngine. You need at least eslint@1.0.0```

I believe vscode-eslint has already implemented these changes:

https://github.com/microsoft/vscode-eslint/issues/972

### PR DESCRIPTION
**Pull request by fannheyward**
closes #117 

1. vscode-eslint 2.0 added settings migration, this is not ported
2. ConfirmExecution has been removed
3. `rulesCustomizations` supports
4. eslintServer.ts supports ESLint 8+, use the new `ESLint` https://eslint.org/docs/user-guide/migrating-to-7.0.0#deprecate-cliengine

### CODE REVIEW

**Comment by tstirrat15** [comment]
Thank you for putting in the work on this! Is there anything I/we can do to help this get through?

**Comment by tstirrat15** [comment]
To clarify: I want to uninstall `coc-eslint`, right?

**Comment by tstirrat15** [comment]
Sure, no worries. The autofix issue is just a part of it - it's also not highlighting anything. There's nothing in `:CocInfo` that would indicate an error, though. Lemme know if there's other diagnostics I can provide.

**Comment by skilbjo** [comment]
> @tstirrat15 you can try this work or not with your project.
> 
> 1. `:CocUninstall coc-tsserver` to uninstall the old release
> 2. clone the repo and checkout this PR
> 3. `yarn install && yarn build`
> 4. `set runtimepath^=~/src/coc-eslint` in your vimrc
> 
> That's all, you're now using this PR coc-eslint.

One note to these instructions, you need to check out the correct branch (`feat/eslint-8`). Here are my edits:

```
- :CocUninstall coc-eslint
- git clone fannheyward/coc-eslint ~/dev/coc-eslint
- cd ~/dev/coc-eslint && git checkout feat/eslint-8
- yarn install && yarn build
- (in `~/.vimrc`) set runtimepath^=~/dev/coc-eslint
```

Working great for me so far @fannheyward . Any word when you plan to merge?

**Comment by tstirrat15** [comment]
Seconding - everything worked well. Thank you!

**Comment by jougene** [comment]
When it can be merged?

**Comment by Seb-C** [comment]
@chemzqm Are you still maintaining this project?
I think we are a lot to wait for this major issue to be fixed, so it would be useful to know if we can expect it to be merged any soon or if someone should take the lead and fork it.
Thank you :bow:

**Comment by fannheyward** [comment]
Hello guys, I just published https://www.npmjs.com/package/coc-eslint8, with this PR ESLint 8 support. You can `:CocUninstall coc-eslint` and `:CocInstall coc-eslint8`.

Note that: after chemzqm came back and merge this PR, the you should use back `coc-eslint`.

**Comment by Seb-C** [comment]
@fannheyward Thank you so much! It works perfectly for me :heart: .

**Comment by EvgeniyRRU** [comment]
@fannheyward, is https://www.npmjs.com/package/coc-eslint8 supports `eslint7`?

**Comment by fannheyward** [comment]
@EvgeniyRRU yes

**Comment by dannobytes** [comment]
Thank you so much for fixing this @fannheyward !! 👏🏼

**Comment by adelin-b** [comment]
> Hello guys, I just published https://www.npmjs.com/package/coc-eslint8, with this PR ESLint 8 support. You can `:CocUninstall coc-eslint` and `:CocInstall coc-eslint8`.
> 
> Note that: after chemzqm came back and merge this PR, the you should use back `coc-eslint`.

Thank you a lot, could you add the reasons in the Readme of the package ? I was randomly looking through coc marketplace and thought it was a scam package as it state v2.0.0 while the original package is v1.4.5 I think. Almost reported it

**Comment by yaegassy** [comment]
@chemzqm ping

**Review by chemzqm — APPROVED** [review]

**Comment by fannheyward** [comment]
To anyone who use coc-eslint8, you should use [coc-eslint ](https://www.npmjs.com/package/coc-eslint) 1.5.0 now.

**Comment by nuc** [comment]
@fannheyward Next time you are in Berlin, the beers are on me 🍻

**Pull request merged**
